"""Chat — Build with AI: Save/Close the generated Echo Agent's canvas, then
use its own AI-generated conversation starters (ELITEA-2074).

Coverage boundary (AFS § Coverage decision): the participant-chip/starter-
tile/click-to-populate/Send mechanics this case exercises after canvas-close
are the SAME infrastructure `test_chat_agent_starters_add_remove.py`
(ELITEA-2177/2178/2465, merged) already proves — but that spec's agent is a
disposable, API-seeded agent with hand-written `conversation_starters`. This
case's own precondition is an agent whose name/instructions/welcome message/
starters are ALL AI-generated by Build with AI (ELITEA-2073's own flow), so
none of that content is knowable ahead of a live run. The precondition
(generating the agent) is reproduced fresh in Setup, as transit to reach
this case's own subject.

**Case-text drift, live-confirmed (see AFS § Test Data for the full
writeup):** neither of the case's own illustrative starter texts ("Echo
this: Hello, world!" / "Repeat this 3 times: test") nor its literal
"echoes back exactly"/"exactly 3 times" wording is reproducible — the
starters are AI-generated (never that literal text), and the generated
Echo Agent's own instructions explicitly permit (and demonstrably add) an
"Echo:"-style prefix. This test captures whatever starters actually render
and asserts the agent's reply CONTAINS the exact sent text
(`sent_text in reply_text`), not literal string equality — the live-contract
resolution `.agents/testing.md` § "How to test a NONDETERMINISTIC producer
without substituting it" prescribes.

Spec: test-specs/chat-interface/l2_save-close-and-use-generated-echo-agent-starters_ELITEA-2074.md

Zero new page-object locators or testids were needed (100% reuse of
``ChatPage``, ``AgentCanvasPage``, ``GenerateAgentModalPage``,
``AgentFormPage``).
"""

import logging
import re

import allure
import pytest
from pages.agent_canvas_page import AgentCanvasPage
from pages.agent_form_page import AgentFormPage
from pages.chat_page import ChatPage
from pages.generate_agent_modal_page import GenerateAgentModalPage
from playwright.sync_api import Page, expect

logger = logging.getLogger("elitea.tests.chat.generated_echo_agent_starters")

pytestmark = [pytest.mark.ui, pytest.mark.chat, pytest.mark.agents, pytest.mark.regression, pytest.mark.new]

# ---------------------------------------------------------------------------
# Timeout constants (milliseconds)
# ---------------------------------------------------------------------------
UI_ELEMENT_TIMEOUT = 10_000
NAVIGATION_TIMEOUT = 15_000
LIVE_GENERATE_RESPONSE_TIMEOUT = 45_000
AI_RESPONSE_TIMEOUT = 60_000

PROMPT_TEXT = "generate an echo agent"

# Per the case's own step 3 ("four... buttons") and this project's existing
# starter-count assertion idiom (test_chat_agent_starters_add_remove.py):
# the count is a property of what the LLM generates for this prompt, not a
# UI guarantee — bounded, not a bare ``== 4`` (AFS § step 3 rationale).
MIN_STARTER_COUNT = 1
MAX_STARTER_COUNT = 4


def _conv_id_from_url(page: Page) -> int | None:
    match = re.search(r"/chat/(\d+)", page.url)
    return int(match.group(1)) if match else None


class TestGeneratedEchoAgentSaveCloseAndStarters:
    """ELITEA-2074: Chat – Create Agent with AI Build – Save Agent, Close
    Canvas, and Test with Conversation Starters (l2, high)."""

    @allure.issue(
        "https://github.com/EliteaAI/onetest-ai-tm-Elitea/blob/main/tests/automated-full-regression-ui/"
        "chat/ELITEA-2074_chat-create-agent-with-ai-build-save-agent-close-canvas-and-test-with-conversation-starters.md",
        "onetest-ai Test Case link",
    )
    @pytest.mark.p2
    def test_save_close_and_use_generated_starters(self, page: Page, agent_api, conversation_api):
        """Build an Echo Agent via Build with AI (this case's own stated
        precondition, reproduced fresh for test isolation), verify the
        canvas's populated Welcome Message/Starters sections, verify Save is
        correctly disabled (nothing dirty — the generate flow already
        persisted the full config), close the canvas, then click two of the
        agent's own AI-generated conversation starters and verify each one
        produces a genuine echo of the sent text.

        Steps (AFS
        test-specs/chat-interface/l2_save-close-and-use-generated-echo-agent-starters_ELITEA-2074.md):
        Setup. Generate the Echo Agent via Build with AI (ELITEA-2073's flow).
        1. Canvas shows generated config + model.
        2. Welcome Message / Chat Starters sections populated.
        3. Four starter buttons (bounded 1-4, data-dependent).
        4. Save is disabled (nothing dirty) — case-text drift, asserted directly.
        5. Close canvas (X button).
        6. "Echo Agent | base" shown as active participant.
        7. Starter tiles shown in the conversation area.
        8-9. Click 1st starter, Send, verify the reply echoes the sent text.
        10-11. Click 2nd starter, Send, verify the reply echoes the sent text.
        """
        chat = ChatPage(page)
        agent_canvas = AgentCanvasPage(page)
        agent_form = AgentFormPage(page)
        modal = GenerateAgentModalPage(page)

        agent_id = None
        conv_id = None

        console_messages = []

        def _on_console(msg):
            # Excludes the pre-existing, already-documented `disableUnderline`
            # React-prop warning on GenerateAgentReviewForm.jsx (AFS §
            # Expected Results / test-specs/agents/_surface.md,
            # test-specs/skills/_surface.md carry the same baseline entry).
            if msg.type == "error" and "disableUnderline" not in msg.text:
                console_messages.append(msg)

        page.on("console", _on_console)

        try:
            with allure.step(
                "Setup — build the Echo Agent via Build with AI (ELITEA-2073's "
                "own generate flow, reproduced fresh here as this case's stated "
                "precondition, for test isolation)"
            ):
                chat.navigate_to_chat()
                chat.wait_for_page_load()
                chat.click_create_conversation(timeout=NAVIGATION_TIMEOUT)
                chat.open_create_new_agent_canvas(timeout=NAVIGATION_TIMEOUT)
                agent_canvas.wait_for_open(timeout=UI_ELEMENT_TIMEOUT)
                modal.open_modal(timeout=UI_ELEMENT_TIMEOUT)
                modal.fill_prompt(PROMPT_TEXT)
                modal.generate_button.click()
                modal.wait_for_review_form(timeout=LIVE_GENERATE_RESPONSE_TIMEOUT)
                create_response = modal.click_approve_and_wait_for_agent_created(
                    timeout=UI_ELEMENT_TIMEOUT
                )
                assert create_response.status == 201, (
                    f"Agent-creation POST should resolve 201, got {create_response.status}"
                )
                created_agent = create_response.json()
                agent_id = created_agent.get("id")
                created_agent_name = created_agent.get("name")
                assert agent_id and created_agent_name, (
                    f"Expected a numeric id and non-empty name, got: {created_agent!r}"
                )

            with allure.step(
                "Step 1 — Verify the agent canvas shows the generated config "
                "with LLM model displayed"
            ):
                expect(agent_canvas.title).to_have_text(created_agent_name, timeout=UI_ELEMENT_TIMEOUT)
                # Same idiom as test_chat_agent_starters_add_remove.py's own
                # LLM-label check — assert non-empty, not a literal model
                # name (the selected/default model is not something this
                # case's own flow controls or predicts).
                expect(chat.model_selector_name).to_be_visible(timeout=UI_ELEMENT_TIMEOUT)
                assert (chat.model_selector_name.text_content() or "").strip(), (
                    "Model selector should show a non-empty LLM model name in the canvas"
                )

            with allure.step(
                "Step 2 — Scroll to view WELCOME MESSAGE and CHAT STARTERS "
                "sections; verify both are populated"
            ):
                expect(agent_canvas.get_section_header("welcome-message")).to_be_visible(
                    timeout=UI_ELEMENT_TIMEOUT
                )
                expect(agent_canvas.get_section_header("chat-starters")).to_be_visible(
                    timeout=UI_ELEMENT_TIMEOUT
                )
                # "Populated" means non-empty CONTENT, not merely a visible
                # header — assert the actual field values Build with AI wrote.
                # Web-first (retrying), not a one-shot input_value() read:
                # same async-settle gotcha already confirmed for Save/
                # Discard's disabled state right after Create-Agent (memory:
                # build_with_ai_post_create_save_discard_disabled_state_
                # settles_async.md) — the canvas's own form fields re-
                # hydrate from the just-created agent a moment after the
                # create POST resolves, and a bare .input_value() read can
                # catch the pre-hydration empty state (confirmed live: R1
                # caught a transient empty Welcome Message this way).
                expect(agent_form.welcome_message_input).not_to_have_value(
                    "", timeout=UI_ELEMENT_TIMEOUT
                )
                starter_input_count = agent_form.conversation_starter_inputs.count()
                assert starter_input_count > 0, (
                    "Chat Starters section should have at least one generated starter input"
                )
                for i in range(starter_input_count):
                    expect(agent_form.conversation_starter_inputs.nth(i)).not_to_have_value(
                        "", timeout=UI_ELEMENT_TIMEOUT
                    )

            with allure.step(
                "Step 3 — Verify conversation starter buttons are displayed "
                "(case: four; asserted as a bounded, data-dependent count — "
                "see AFS step 3 rationale)"
            ):
                chat.get_chat_starter_tiles().first.wait_for(state="visible", timeout=UI_ELEMENT_TIMEOUT)
                starter_count = chat.get_chat_starter_tiles().count()
                assert MIN_STARTER_COUNT <= starter_count <= MAX_STARTER_COUNT, (
                    f"Expected {MIN_STARTER_COUNT}-{MAX_STARTER_COUNT} generated conversation "
                    f"starter tiles, got {starter_count}"
                )

            with allure.step(
                "Step 4 — Click Save; verify it is correctly DISABLED (case-text "
                "drift, CLARIFICATION — the generate flow's own Create-Agent "
                "call already persisted the full config, nothing left dirty)"
            ):
                # Web-first (retrying) assertions, not a one-shot ``is_disabled()``
                # read — the disabled state settles asynchronously right after
                # the create POST resolves (confirmed live: an immediate read
                # can catch a transient enabled moment before React settles).
                # Save is DISABLED (not clicked — nothing dirty to persist,
                # the create POST already saved the full generated config).
                expect(agent_canvas.discard_button).to_be_disabled(timeout=UI_ELEMENT_TIMEOUT)
                expect(agent_form.save_button).to_be_disabled(timeout=UI_ELEMENT_TIMEOUT)

            with allure.step("Step 5 — Click the X button to close the canvas panel"):
                agent_canvas.close(timeout=UI_ELEMENT_TIMEOUT)
                expect(page).to_have_url(re.compile(r"/chat$"), timeout=UI_ELEMENT_TIMEOUT)

            with allure.step(
                'Step 6 — Verify "{name} | base" is listed as an active '
                "participant in the message input area"
            ):
                expect(chat.switch_participant_button).to_be_visible(timeout=UI_ELEMENT_TIMEOUT)
                expect(chat.switch_participant_button).to_contain_text(created_agent_name)
                expect(chat.chat_version_selector_trigger).to_have_text("base", timeout=UI_ELEMENT_TIMEOUT)

            with allure.step(
                "Step 7 — Verify the conversation starter buttons appear in the "
                "main conversation area"
            ):
                tiles = chat.get_chat_starter_tiles()
                expect(tiles.first).to_be_visible(timeout=UI_ELEMENT_TIMEOUT)
                assert tiles.count() == starter_count, (
                    "Same starter tile count should render in the conversation area "
                    "as in the canvas's own Chat Starters section"
                )
                starter_texts = [
                    (tiles.nth(i).text_content() or "").strip() for i in range(tiles.count())
                ]

            with allure.step(
                "Step 8 — Click the first conversation starter; verify it is sent "
                "as a message"
            ):
                initial_count = chat.get_message_count()
                first_starter_text = chat.click_chat_starter_tile(starter_texts[0], timeout=UI_ELEMENT_TIMEOUT)
                assert chat.message_input.input_value() == first_starter_text, (
                    "Message input should be pre-filled with the clicked starter's exact text"
                )
                chat.send_button.click()
                chat.wait_for_message_count(initial_count + 1, timeout=UI_ELEMENT_TIMEOUT)
                if conv_id is None:
                    conv_id = _conv_id_from_url(page)

            with allure.step(
                "Step 9 — Verify the Echo Agent responds by echoing back the "
                "sent text (live-contract: containment, not literal equality — "
                "see AFS § Test Data / case-text drift)"
            ):
                chat.wait_for_ai_response(initial_count=initial_count, timeout=AI_RESPONSE_TIMEOUT)
                reply_text_1 = chat.get_last_message_text()
                assert first_starter_text in reply_text_1, (
                    f"Agent reply should contain the exact sent text {first_starter_text!r}, "
                    f"got: {reply_text_1!r}"
                )

            with allure.step("Step 10 — Click the second conversation starter; verify it is sent"):
                # MIN_STARTER_COUNT permits a data-dependent generation of
                # only 1 starter (AFS step 3 rationale) — in that case steps
                # 10-11 genuinely cannot run. Fail with a clear, attributed
                # message rather than a bare IndexError on starter_texts[1].
                assert starter_count >= 2, (
                    f"Steps 10-11 require a second generated conversation starter to "
                    f"click, but this run's Build-with-AI draft produced only "
                    f"{starter_count} (bounded {MIN_STARTER_COUNT}-{MAX_STARTER_COUNT} "
                    "per AFS step 3 rationale — a genuinely data-dependent outcome, "
                    "not a defect)"
                )
                initial_count = chat.get_message_count()
                second_starter_text = chat.click_chat_starter_tile(starter_texts[1], timeout=UI_ELEMENT_TIMEOUT)
                assert chat.message_input.input_value() == second_starter_text
                chat.send_button.click()
                chat.wait_for_message_count(initial_count + 1, timeout=UI_ELEMENT_TIMEOUT)

            with allure.step(
                "Step 11 — Verify the agent responds by echoing back the second "
                "sent text (same live-contract resolution as step 9)"
            ):
                chat.wait_for_ai_response(initial_count=initial_count, timeout=AI_RESPONSE_TIMEOUT)
                reply_text_2 = chat.get_last_message_text()
                assert second_starter_text in reply_text_2, (
                    f"Agent reply should contain the exact sent text {second_starter_text!r}, "
                    f"got: {reply_text_2!r}"
                )

            with allure.step("Side-channel check — zero console errors across the whole flow"):
                assert not console_messages, f"Unexpected console errors: {console_messages}"
        finally:
            with allure.step("Cleanup — delete the conversation and the created agent"):
                if conv_id:
                    try:
                        conversation_api.delete_conversation(conv_id)
                        logger.info("Deleted conversation %s", conv_id)
                    except Exception as exc:
                        logger.warning("Cleanup failed for conversation %s: %s", conv_id, exc)
                if agent_id:
                    try:
                        agent_api.delete_agent(agent_id)
                        logger.info("Deleted agent %s", agent_id)
                    except Exception as exc:
                        logger.warning("Cleanup failed for agent %s: %s", agent_id, exc)
