"""UI Tests for the Skill "Build with AI" generation flow.

Covers ELITEA-2001: generation failure shows an error, preserves the
entered prompt, and a retry (re-clicking the same Generate button) succeeds
once the service recovers.

Covers ELITEA-1990: the generated draft's review-form fields (Name,
Description, Instructions) are editable before creation, and the skill is
created with the edited values (not the originally-generated ones).

Covers ELITEA-1989 (extend-existing gap fill): the loading state shown
during generation displays the exact text "Generating skill draft...", and
the resulting review form shows only Name/Description/Instructions — no
tools/agents/pipelines/toolkits/MCPs/resources section is rendered.

Covers ELITEA-1988 (extend-existing gap fill): standalone, first-class
visibility assertions that clicking "Build with AI" opens the modal, and
that the modal displays a prompt input, a "Generate" button, and a
"Cancel" button — the latter never referenced by any other test in this
file before this gap fill.

Covers ELITEA-1991 (extend-existing gap fill): clicking "Create Skill"
directly on an unmodified generated draft (no edits) persists the
*generated* values verbatim, redirects to the Skill details page showing
those values, and the new skill appears in the Skills list — the
through-line ELITEA-1990's test does not cover, since that test always
edits the review form before creating.

Covers ELITEA-1993: the review-form Name field enforces its naming rules
(lowercase letters/digits/hyphens only, no leading/trailing hyphen, <=64
chars) on manual edits — disabling "Create Skill" and showing the
validation-error helper text for each invalid variant, and never letting a
Skill be created with an invalid name. The 64-char variant is asserted per
the AFS's corrected expectation: the field's native `maxlength` truncates
any input to 64 chars before validation ever sees an over-length value, so
that state is unreachable via manual editing and the field stays valid.

Covers ELITEA-1992: the Skill name generated by a REAL, UNMOCKED call to
the generate-draft endpoint adheres to the same naming rules — lowercase
letters/digits/hyphens only, no leading/trailing hyphen, <=64 chars. This
is the one test in the file that deliberately does NOT mock
`generate_skill_draft`, so it verifies the platform's actual AI/backend
naming behavior rather than an analyst-chosen fixture string.

Covers ELITEA-1996: clicking "Back to prompt" (`back_button`) on the
REVIEW step returns the modal to the INPUT step — review-form fields and
the review-step action row removed from the DOM, not merely hidden —
while preserving the exact previously-typed prompt text and firing no new
network request. Skills-entity sibling of ELITEA-1919
(tests/ui/agents/test_agent_build_with_ai.py); same shared
GenerateEntityModal.jsx mechanism (`handleBack()` resets `step`/`draftData`
but never calls `setDescription('')`), verified independently here for the
Skill entity's own DOM/testids.

Spec: test-specs/skills/l2_build-with-ai-generation-failure-retry_ELITEA-2001.md
Spec: test-specs/skills/l2_generated-skill-draft-fields-are-editable-before-creation_ELITEA-1990.md
Spec: test-specs/skills/lextend_skill-draft-generated-from-natural-language-description_ELITEA-1989.md
Spec: test-specs/skills/lextend_clicking-build-with-ai-opens-the-generation-modal_ELITEA-1988.md
Spec: test-specs/skills/lextend_create-skill-from-draft-saves-and-redirects-to-skill-details_ELITEA-1991.md
Spec: test-specs/skills/l2_build-with-ai-name-field-validation_ELITEA-1993.md
Spec: test-specs/skills/l2_generated-skill-name-adheres-to-naming-rules_ELITEA-1992.md
Spec: test-specs/skills/l2_build-with-ai-back-to-prompt-returns-to-input-step-preserves-text_ELITEA-1996.md
Covers: GenerateSkillModal (GenerateEntityModal.jsx via GenerateSkillModal.jsx)

Shares the modal-shell behavior with the Agent flow
(tests/ui/agents/test_agent_build_with_ai.py) via
GenerateEntityModalPageBase — but is a genuinely separate business object
(Skill, not Agent): distinct entry point, endpoint, and review-form field
set (Name/Description/Instructions only — no Welcome Message/conversation
starters).

Markers:
    - ui: requires browser
    - skills: skill-related tests
    - p2: medium priority (case priority: medium)

Usage:
    cd automation
    pytest tests/ui/skills/test_skill_build_with_ai.py -v
"""

import re

import allure
import pytest

from pages.skills_list_page import SkillsListPage
from pages.skill_detail_page import SkillDetailPage
from pages.generate_skill_modal_page import GenerateSkillModalPage

pytestmark = [pytest.mark.ui, pytest.mark.skills, pytest.mark.new]

# ---------------------------------------------------------------------------
# Timeout constants (milliseconds)
# ---------------------------------------------------------------------------
NAVIGATION_TIMEOUT = 15000
GENERATE_RESPONSE_TIMEOUT = 15000
LOADING_STATE_TIMEOUT = 3000
REVIEW_FORM_TIMEOUT = 15000
CREATE_RESPONSE_TIMEOUT = 15000

PROMPT_TEXT = (
    "Create a skill that summarizes long customer support transcripts into "
    "a 3-bullet action list for the assigned agent."
)
SIMULATED_ERROR_MESSAGE = "Simulated generation failure for ELITEA-2001"

# Exact validation-error helper text for an invalid Name (skillDraftValidation
# .helpers.js's SKILL_NAME_RE branch) — confirmed against source by the AFS
# (ELITEA-1993) and reused verbatim here rather than re-derived.
NAME_VALIDATION_ERROR = (
    "Name must be lowercase letters, digits and hyphens only, "
    "cannot start or end with a hyphen"
)

# Minimal, valid draft payload mirroring the real generate_skill_draft
# response shape (GenerateSkillModal.jsx / GenerateSkillReviewForm.jsx) —
# used for the retry's synthetic recovery (option (b) per the AFS). Unlike
# the Agent draft payload, the Skill review form only surfaces
# Name/Description/Instructions (no welcome_message/conversation_starters).
RETRY_DRAFT_PAYLOAD = {
    "name": "support-transcript-summarizer",
    "description": "Summarizes long customer support transcripts into a 3-bullet action list.",
    "instructions": "You are a support transcript summarizer. Read the transcript and "
                     "produce a structured 3-bullet action-item summary for the assigned agent.",
}


class TestSkillBuildWithAIGenerationFailureRetry:
    """Build with AI (P2): generation failure shows error, prompt is
    preserved, and retry succeeds once the service recovers."""

    @allure.issue(
        "https://github.com/EliteaAI/onetest-ai-tm-Elitea/blob/main/tests/automated-full-regression-ui/"
        "skills/build_with_ai/ELITEA-2001_build-with-ai-generation-failure-shows-error-and-allows-retry.md",
        "onetest-ai Test Case link",
    )
    @pytest.mark.p2
    @pytest.mark.regression
    def test_generation_failure_shows_error_and_allows_retry(self, page):
        """Generation failure surfaces an error, preserves the prompt, and a
        retry (via the same Generate button) succeeds once the service
        recovers."""
        list_page = SkillsListPage(page)
        modal = GenerateSkillModalPage(page)

        # ------------------------------------------------------------------
        # Step 1 — Open modal, enter description
        # ------------------------------------------------------------------
        with allure.step("Step 1 — Open modal, enter description"):
            list_page.navigate_to_create()
            modal.open_modal()

            assert not modal.is_generate_enabled(), (
                "Generate button should be disabled while the prompt is empty"
            )

            modal.fill_prompt(PROMPT_TEXT)

            assert modal.get_prompt_value() == PROMPT_TEXT, (
                "Prompt textarea should contain exactly the entered text"
            )
            assert modal.is_generate_enabled(), (
                "Generate button should become enabled once the prompt is non-empty"
            )

        # ------------------------------------------------------------------
        # Step 2 — Trigger/simulate generation failure
        # ------------------------------------------------------------------
        with allure.step("Step 2 — Trigger/simulate generation failure"):
            modal.mock_generate_failure(SIMULATED_ERROR_MESSAGE, status=500)
            response = modal.click_generate_and_wait_for_response(timeout=GENERATE_RESPONSE_TIMEOUT)

            assert response.status == 500, (
                f"Expected the mocked generate-draft request to resolve 500, got {response.status}"
            )
            modal.wait_for_input_step(timeout=LOADING_STATE_TIMEOUT)

        # ------------------------------------------------------------------
        # Step 3 — Verify clear error message displayed
        # ------------------------------------------------------------------
        with allure.step("Step 3 — Verify clear error message displayed"):
            assert modal.is_error_alert_visible(), (
                "An error alert should be displayed in the modal after a generation failure"
            )
            assert modal.get_error_message() == SIMULATED_ERROR_MESSAGE, (
                "Error alert should surface the backend's error message verbatim, "
                f"got: {modal.get_error_message()!r}"
            )

        # ------------------------------------------------------------------
        # Step 4 — Verify the previously entered prompt is still present
        # ------------------------------------------------------------------
        with allure.step("Step 4 — Verify the previously entered prompt is still present"):
            assert modal.get_prompt_value() == PROMPT_TEXT, (
                "Prompt text entered before the failure should still be visible after the failure"
            )

        # ------------------------------------------------------------------
        # Step 5 — Click retry / "Generate" button
        # ------------------------------------------------------------------
        with allure.step('Step 5 — Click retry / "Generate" button'):
            modal.clear_generate_mock()
            modal.mock_generate_success(RETRY_DRAFT_PAYLOAD)

            with modal.expect_generate_response(timeout=GENERATE_RESPONSE_TIMEOUT) as retry_response_info:
                modal.generate_button.click()

                # resetGenerate() fires before the retry request — the stale
                # Step 3 error should be gone as soon as the retry is in
                # flight, not only once the new (artificially delayed)
                # request resolves.
                modal.error_alert.wait_for(state="hidden", timeout=LOADING_STATE_TIMEOUT)
                modal.wait_for_loading_visible(timeout=LOADING_STATE_TIMEOUT)

        # ------------------------------------------------------------------
        # Step 6 — Verify the retry succeeds and a draft is returned
        # ------------------------------------------------------------------
        with allure.step("Step 6 — Verify the retry succeeds and a draft is returned"):
            retry_response = retry_response_info.value
            assert retry_response.status == 200, (
                f"Expected the retried generate-draft request to succeed, got {retry_response.status}"
            )
            assert retry_response.json()["name"] == RETRY_DRAFT_PAYLOAD["name"], (
                "Retried request should resolve with the recovered draft payload"
            )

            modal.wait_for_input_step_hidden(timeout=1000)
            modal.wait_for_review_form(timeout=REVIEW_FORM_TIMEOUT)


# ---------------------------------------------------------------------------
# ELITEA-1990 — review-form fields editable before creation
# ---------------------------------------------------------------------------

REVIEW_PROMPT_TEXT = (
    "Create a skill that reviews pull request diffs and flags missing test "
    "coverage."
)

# Synthetic draft returned by the mocked generate-draft call — the review
# form is pre-populated with these values before any user edit.
GENERATED_DRAFT_PAYLOAD = {
    "name": "pr-test-coverage-review",
    "description": "Reviews pull request diffs and flags missing test coverage.",
    "instructions": "You are a PR reviewer. Inspect the diff and flag any "
                     "changed code paths that lack corresponding test coverage.",
}

# User edits applied on top of the generated draft — the case's core
# assertion is that these values (not GENERATED_DRAFT_PAYLOAD's) end up on
# the created skill.
EDITED_NAME = "edited-pr-coverage-skill-v2"
EDITED_DESCRIPTION = "Testid-verified edited description for ELITEA-1990."
EDITED_INSTRUCTIONS = "Testid-verified edited instructions for ELITEA-1990."

# ---------------------------------------------------------------------------
# ELITEA-1991 — create skill from an unmodified draft
# ---------------------------------------------------------------------------

UNMODIFIED_PROMPT_TEXT = (
    "Create a skill that reviews changelog entries and rewrites them in a "
    "consistent, user-facing tone."
)

# Distinct from GENERATED_DRAFT_PAYLOAD (ELITEA-1990) so the two sibling
# tests never share created-skill names, even though route mocks are
# scoped per-page and don't actually collide.
UNMODIFIED_DRAFT_PAYLOAD = {
    "name": "changelog-editor",
    "description": "Reviews and rewrites changelog entries in a consistent, "
                    "user-facing tone.",
    "instructions": "You are a changelog editor. Rewrite technical commit "
                     "messages and internal notes into clear, benefit-focused "
                     "updates that help users understand what changed and why "
                     "it matters.",
}


class TestSkillBuildWithAIReviewFormEditableFields:
    """Build with AI (P2): the generated draft's review-form fields (Name,
    Description, Instructions) accept user edits before creation, and the
    created skill reflects the edited values, not the originally-generated
    ones.

    Also covers ELITEA-1989 (extend-existing gap fill, see
    ``test_loading_state_shows_exact_text_and_review_form_has_no_extra_sections``
    below): the loading state's exact text during generation, and the
    absence of any tools/agents/pipelines/toolkits/MCPs/resources section on
    the review form.

    Also covers ELITEA-1991 (extend-existing gap fill, see
    ``test_create_skill_from_unmodified_draft_persists_generated_values``
    below): clicking "Create Skill" with the review form left completely
    unmodified persists the *generated* values verbatim, and the created
    skill is visible in the Skills list — the two gaps this sibling class's
    always-edit test does not cover."""

    @allure.issue(
        "https://github.com/EliteaAI/onetest-ai-tm-Elitea/blob/main/tests/automated-full-regression-ui/"
        "skills/build_with_ai/ELITEA-1990_generated-skill-draft-fields-are-editable-before-creation.md",
        "onetest-ai Test Case link",
    )
    @pytest.mark.p2
    @pytest.mark.regression
    def test_review_form_fields_are_editable_before_creation(self, page, skill_api):
        """Overwriting the generated draft's Name/Description/Instructions
        in the review form persists the edits, and creating the skill from
        the edited form produces a skill with the edited (not generated)
        values."""
        list_page = SkillsListPage(page)
        modal = GenerateSkillModalPage(page)
        skill_id = None

        try:
            # ------------------------------------------------------------
            # Step 1 — Open modal, enter prompt
            # ------------------------------------------------------------
            with allure.step("Step 1 — Open modal, enter prompt"):
                list_page.navigate_to_create()
                modal.open_modal()

                assert not modal.is_generate_enabled(), (
                    "Generate button should be disabled while the prompt is empty"
                )

                modal.fill_prompt(REVIEW_PROMPT_TEXT)

                assert modal.is_generate_enabled(), (
                    "Generate button should become enabled once the prompt is non-empty"
                )

            # ------------------------------------------------------------
            # Step 2 — Generate the draft, reach the review-form step
            # ------------------------------------------------------------
            with allure.step("Step 2 — Generate the draft, reach the review-form step"):
                modal.mock_generate_success(GENERATED_DRAFT_PAYLOAD)
                response = modal.click_generate_and_wait_for_response(
                    timeout=GENERATE_RESPONSE_TIMEOUT
                )

                assert response.status == 200, (
                    f"Expected the mocked generate-draft request to resolve 200, got {response.status}"
                )
                modal.wait_for_review_form(timeout=REVIEW_FORM_TIMEOUT)

                assert modal.get_review_name() == GENERATED_DRAFT_PAYLOAD["name"], (
                    "Review form should be pre-populated with the generated draft's name"
                )
                assert modal.get_review_description() == GENERATED_DRAFT_PAYLOAD["description"], (
                    "Review form should be pre-populated with the generated draft's description"
                )
                assert modal.get_review_instructions() == GENERATED_DRAFT_PAYLOAD["instructions"], (
                    "Review form should be pre-populated with the generated draft's instructions"
                )

            # ------------------------------------------------------------
            # Step 3 — Modify the generated Name
            # ------------------------------------------------------------
            with allure.step("Step 3 — Modify the generated Name"):
                modal.set_review_name(EDITED_NAME)

                assert modal.get_review_name() == EDITED_NAME, (
                    "Name field should accept and display the edited value"
                )

            # ------------------------------------------------------------
            # Step 4 — Modify the generated Description
            # ------------------------------------------------------------
            with allure.step("Step 4 — Modify the generated Description"):
                modal.set_review_description(EDITED_DESCRIPTION)

                assert modal.get_review_description() == EDITED_DESCRIPTION, (
                    "Description field should accept and display the edited value"
                )

            # ------------------------------------------------------------
            # Step 5 — Modify the generated Instructions; verify all three
            # edits persist simultaneously
            # ------------------------------------------------------------
            with allure.step("Step 5 — Modify Instructions; verify all three fields hold their edits"):
                modal.set_review_instructions(EDITED_INSTRUCTIONS)

                assert modal.get_review_instructions() == EDITED_INSTRUCTIONS, (
                    "Instructions field should accept and display the edited value"
                )
                # All three edits must be present at once — not just each in
                # isolation immediately after being typed.
                assert modal.get_review_name() == EDITED_NAME
                assert modal.get_review_description() == EDITED_DESCRIPTION
                assert modal.get_review_instructions() == EDITED_INSTRUCTIONS

            # ------------------------------------------------------------
            # Step 6 — Click "Create Skill"
            # ------------------------------------------------------------
            with allure.step('Step 6 — Click "Create Skill"'):
                with page.expect_response(
                    lambda r: "/elitea_core/skills/prompt_lib/" in r.url
                    and r.request.method == "POST",
                    timeout=CREATE_RESPONSE_TIMEOUT,
                ) as create_response_info:
                    modal.approve_button.click()

                create_response = create_response_info.value
                assert create_response.status == 201, (
                    f"Expected skill creation to resolve 201, got {create_response.status}"
                )

            # ------------------------------------------------------------
            # Step 7 — Verify redirect to the created skill's detail page,
            # with the edited (not generated) values
            # ------------------------------------------------------------
            with allure.step("Step 7 — Verify redirect and edited values on the detail page"):
                page.wait_for_url(re.compile(r".*/skills/all/\d+$"), timeout=NAVIGATION_TIMEOUT)

                skill_id_match = re.search(r"/skills/all/(\d+)$", page.url)
                assert skill_id_match, (
                    f"Expected a numeric skill id in the redirect URL, got: {page.url}"
                )
                skill_id = int(skill_id_match.group(1))

                detail_page = SkillDetailPage(page)
                detail_page.wait_for_page_load()

                assert detail_page.get_name() == EDITED_NAME, (
                    "Created skill should show the edited Name, not the generated draft's"
                )
                assert detail_page.get_description() == EDITED_DESCRIPTION, (
                    "Created skill should show the edited Description, not the generated draft's"
                )
                assert detail_page.get_instructions() == EDITED_INSTRUCTIONS, (
                    "Created skill should show the edited Instructions, not the generated draft's"
                )
                # Explicit contrast against the original generated values —
                # this is the case's core assertion (edited, not generated).
                assert detail_page.get_name() != GENERATED_DRAFT_PAYLOAD["name"]
                assert detail_page.get_description() != GENERATED_DRAFT_PAYLOAD["description"]
                assert detail_page.get_instructions() != GENERATED_DRAFT_PAYLOAD["instructions"]
        finally:
            # Cleanup (not a case step — no allure.step needed): delete the
            # created skill via the API (cookie auth), never a raw fetch()
            # from page JS context — that CORS-fails on this app (AFS Known
            # Defect #2).
            if skill_id is not None:
                skill_api.delete_skill(skill_id)

    # ------------------------------------------------------------------
    # ELITEA-1991 — extend-existing gap fill: create skill from an
    # unmodified draft (no edits at all), verify the *generated* values
    # persist on the detail page, and verify the new skill appears in the
    # Skills list. All handles reused from the sibling ELITEA-1990 test
    # above; no new testids or locators added by this test.
    # ------------------------------------------------------------------

    @allure.issue(
        "https://github.com/EliteaAI/onetest-ai-tm-Elitea/blob/main/tests/automated-full-regression-ui/"
        "skills/build_with_ai/ELITEA-1991_create-skill-from-draft-saves-and-redirects-to-skill-details.md",
        "onetest-ai Test Case link",
    )
    @pytest.mark.p2
    @pytest.mark.regression
    def test_create_skill_from_unmodified_draft_persists_generated_values(self, page, skill_api):
        """Clicking "Create Skill" directly on a freshly generated draft —
        with no edits to Name/Description/Instructions — creates the skill
        with the generated values verbatim, redirects to its detail page
        showing those values, and the new skill appears in the Skills
        list."""
        list_page = SkillsListPage(page)
        modal = GenerateSkillModalPage(page)
        skill_id = None

        console_warnings = []
        page.on(
            "console",
            lambda msg: console_warnings.append(msg.text) if msg.type == "warning" else None,
        )

        try:
            # ------------------------------------------------------------
            # Step 1 — Open modal, enter prompt
            # ------------------------------------------------------------
            with allure.step("Step 1 — Open modal, enter prompt"):
                list_page.navigate_to_create()
                modal.open_modal()

                assert not modal.is_generate_enabled(), (
                    "Generate button should be disabled while the prompt is empty"
                )

                modal.fill_prompt(UNMODIFIED_PROMPT_TEXT)

                assert modal.is_generate_enabled(), (
                    "Generate button should become enabled once the prompt is non-empty"
                )

            # ------------------------------------------------------------
            # Step 2 — Generate the draft, reach the review-form step
            # ------------------------------------------------------------
            with allure.step("Step 2 — Generate the draft, reach the review-form step"):
                modal.mock_generate_success(UNMODIFIED_DRAFT_PAYLOAD)
                response = modal.click_generate_and_wait_for_response(
                    timeout=GENERATE_RESPONSE_TIMEOUT
                )

                assert response.status == 200, (
                    f"Expected the mocked generate-draft request to resolve 200, got {response.status}"
                )
                modal.wait_for_review_form(timeout=REVIEW_FORM_TIMEOUT)

            # ------------------------------------------------------------
            # Step 3 — Review the generated Name/Description/Instructions
            # without modifying any of them
            # ------------------------------------------------------------
            with allure.step("Step 3 — Review generated values without modifying them"):
                generated_name = modal.get_review_name()
                generated_description = modal.get_review_description()
                generated_instructions = modal.get_review_instructions()

                assert generated_name == UNMODIFIED_DRAFT_PAYLOAD["name"], (
                    "Review form should be pre-populated with the generated draft's name"
                )
                assert generated_description == UNMODIFIED_DRAFT_PAYLOAD["description"], (
                    "Review form should be pre-populated with the generated draft's description"
                )
                assert generated_instructions == UNMODIFIED_DRAFT_PAYLOAD["instructions"], (
                    "Review form should be pre-populated with the generated draft's instructions"
                )
                # No set_review_*() calls anywhere in this test — the point
                # is to leave the review form entirely untouched.

            # ------------------------------------------------------------
            # Step 4 — Click "Create Skill" with no edits made
            # ------------------------------------------------------------
            with allure.step('Step 4 — Click "Create Skill" with no edits'):
                with page.expect_response(
                    lambda r: "/elitea_core/skills/prompt_lib/" in r.url
                    and r.request.method == "POST",
                    timeout=CREATE_RESPONSE_TIMEOUT,
                ) as create_response_info:
                    modal.approve_button.click()

                create_response = create_response_info.value
                assert create_response.status == 201, (
                    f"Expected skill creation to resolve 201, got {create_response.status}"
                )
                assert not console_warnings, (
                    f"Expected zero console warnings during skill creation, got: {console_warnings}"
                )

            # ------------------------------------------------------------
            # Step 5 — Verify redirect to the created skill's detail page
            # ------------------------------------------------------------
            with allure.step("Step 5 — Verify redirect to the Skill details page"):
                page.wait_for_url(re.compile(r".*/skills/all/\d+$"), timeout=NAVIGATION_TIMEOUT)

                skill_id_match = re.search(r"/skills/all/(\d+)$", page.url)
                assert skill_id_match, (
                    f"Expected a numeric skill id in the redirect URL, got: {page.url}"
                )
                skill_id = int(skill_id_match.group(1))

            # ------------------------------------------------------------
            # Step 6 — Verify the detail page holds the generated
            # (unmodified) values — the contrast with ELITEA-1990, which
            # proves edited values win
            # ------------------------------------------------------------
            with allure.step("Step 6 — Verify detail page shows the generated values, unmodified"):
                detail_page = SkillDetailPage(page)
                detail_page.wait_for_page_load()

                assert detail_page.get_name() == generated_name, (
                    "Created skill should show the generated Name, unmodified"
                )
                assert detail_page.get_description() == generated_description, (
                    "Created skill should show the generated Description, unmodified"
                )
                assert detail_page.get_instructions() == generated_instructions, (
                    "Created skill should show the generated Instructions, unmodified"
                )

            # ------------------------------------------------------------
            # Step 7 — Navigate to the Skills list and verify the new
            # Skill appears there
            # ------------------------------------------------------------
            with allure.step("Step 7 — Verify the new Skill appears in the Skills list"):
                list_page.navigate()

                assert list_page.skill_exists_in_list(generated_name), (
                    f"Newly created skill {generated_name!r} should appear in the Skills list"
                )
        finally:
            # Cleanup (not a case step — no allure.step needed): delete the
            # created skill via the API (cookie auth), same pattern as the
            # sibling ELITEA-1990 test above.
            if skill_id is not None:
                skill_api.delete_skill(skill_id)

    # ------------------------------------------------------------------
    # ELITEA-1989 — extend-existing gap fill: loading-state exact text +
    # absence of any tools/agents/pipelines/toolkits/MCPs/resources section
    # on the review form. Both handles (`generate-skill-loading-indicator`,
    # the three `review_*_input` fields) already exist on
    # `GenerateSkillModalPage`/`GenerateEntityModalPageBase` — no new
    # testids or locators added by this test.
    # ------------------------------------------------------------------

    @allure.issue(
        "https://github.com/EliteaAI/onetest-ai-tm-Elitea/blob/main/tests/automated-full-regression-ui/"
        "skills/build_with_ai/ELITEA-1989_skill-draft-generated-from-natural-language-description.md",
        "onetest-ai Test Case link",
    )
    @pytest.mark.p1
    @pytest.mark.regression
    def test_loading_state_shows_exact_text_and_review_form_has_no_extra_sections(self, page):
        """During generation, the loading indicator displays the exact text
        "Generating skill draft...", and once the review form is shown it
        contains only the Name/Description/Instructions fields — no
        tools/agents/pipelines/toolkits/MCPs/resources section renders."""
        list_page = SkillsListPage(page)
        modal = GenerateSkillModalPage(page)

        # ------------------------------------------------------------
        # Step 1 — Open modal, enter prompt
        # ------------------------------------------------------------
        with allure.step("Step 1 — Open modal, enter prompt"):
            list_page.navigate_to_create()
            modal.open_modal()

            modal.fill_prompt(REVIEW_PROMPT_TEXT)

            assert modal.get_prompt_value() == REVIEW_PROMPT_TEXT, (
                "Prompt textarea should display the entered description"
            )

            assert modal.is_generate_enabled(), (
                "Generate button should become enabled once the prompt is non-empty"
            )

        # ------------------------------------------------------------
        # Step 2 — Click Generate; verify the loading state shows the
        # exact text "Generating skill draft..." while generation is in
        # flight (mocked, with the shared base's artificial delay_ms so
        # the transient state is reliably observable — same pattern as
        # ELITEA-2001's retry step).
        # ------------------------------------------------------------
        with allure.step('Step 2 — Verify loading state text during generation'):
            modal.mock_generate_success(GENERATED_DRAFT_PAYLOAD)

            with modal.expect_generate_response(timeout=GENERATE_RESPONSE_TIMEOUT) as response_info:
                modal.generate_button.click()
                modal.wait_for_loading_visible(timeout=LOADING_STATE_TIMEOUT)

                assert modal.loading_indicator.text_content() == "Generating skill draft...", (
                    "Loading indicator should display the exact text "
                    "'Generating skill draft...' while a draft is being generated"
                )

            response = response_info.value
            assert response.status == 200, (
                f"Expected the mocked generate-draft request to resolve 200, got {response.status}"
            )
            modal.wait_for_review_form(timeout=REVIEW_FORM_TIMEOUT)

        # ------------------------------------------------------------
        # Step 3 — Verify the review form shows only the three known
        # fields, and no tools/agents/pipelines/toolkits/MCPs/resources
        # section is present anywhere in the dialog.
        # ------------------------------------------------------------
        with allure.step("Step 3 — Verify no extra sections render on the review form"):
            forbidden_terms_pattern = re.compile(
                r"\b(tools?|agents?|pipelines?|toolkits?|mcps?|resources?)\b",
                re.IGNORECASE,
            )
            dialog_text = modal.modal.text_content() or ""
            forbidden_match = forbidden_terms_pattern.search(dialog_text)
            matched_term = forbidden_match.group(0) if forbidden_match else ""

            assert forbidden_match is None, (
                "Review form should not render a tools/agents/pipelines/toolkits/"
                f"MCPs/resources section, but found forbidden term {matched_term!r} "
                "in the dialog"
            )


# ---------------------------------------------------------------------------
# ELITEA-1988 — extend-existing gap fill: standalone, first-class visibility
# assertions that clicking "Build with AI" opens the modal, and that the
# modal's prompt input, Generate button, and Cancel button are all visible.
# All four handles already exist on GenerateSkillModalPage/
# GenerateEntityModalPageBase — no new testids or locators added by this
# test. The Cancel button (`generate-skill-cancel-button`) is referenced by
# no other test in this file before this gap fill.
# ---------------------------------------------------------------------------


class TestSkillBuildWithAIModalElements:
    """Build with AI (P1, smoke): clicking "Build with AI" opens the
    generation modal, and the modal displays the expected static elements —
    a natural-language prompt input, a "Generate" button, and a "Cancel"
    button."""

    @allure.issue(
        "https://github.com/EliteaAI/onetest-ai-tm-Elitea/blob/main/tests/automated-full-regression-ui/"
        "skills/build_with_ai/ELITEA-1988_clicking-build-with-ai-opens-the-generation-modal.md",
        "onetest-ai Test Case link",
    )
    @pytest.mark.p1
    @pytest.mark.smoke
    @pytest.mark.regression
    def test_build_with_ai_opens_modal_with_expected_elements(self, page):
        """Clicking "Build with AI" opens the modal, and the modal shows a
        prompt input, a "Generate" button, and a "Cancel" button — all
        asserted as explicit, standalone visibility checks (no prompt is
        entered, no network call is made; case never reaches the network
        layer)."""
        list_page = SkillsListPage(page)
        modal = GenerateSkillModalPage(page)

        with allure.step("Step 1-2 — Navigate to New Skill screen, click Build with AI"):
            list_page.navigate_to_create()
            modal.open_modal()

            assert modal.modal.is_visible(), (
                "Build with AI modal should be open after clicking the button"
            )

        with allure.step("Step 3 — Verify prompt input is visible"):
            assert modal.prompt_input.is_visible(), (
                "Natural-language prompt input should be visible in the modal"
            )

        with allure.step("Step 4 — Verify Generate button is visible"):
            assert modal.generate_button.is_visible(), (
                "Generate button should be visible in the modal"
            )

        with allure.step("Step 5 — Verify Cancel button is visible"):
            assert modal.cancel_button.is_visible(), (
                "Cancel button should be visible in the modal"
            )


# ---------------------------------------------------------------------------
# ELITEA-1993 — review-form Name field validation on invalid manual edits
# ---------------------------------------------------------------------------


class TestSkillBuildWithAINameFieldValidation:
    """Build with AI (P2): the review-form Name field enforces its naming
    rules on manual edits — "Create Skill" is disabled and a validation
    error is shown for every invalid variant, and no Skill can ever be
    created with an invalid name."""

    @allure.issue(
        "https://github.com/EliteaAI/onetest-ai-tm-Elitea/blob/main/tests/automated-full-regression-ui/"
        "skills/build_with_ai/ELITEA-1993_build-with-ai-name-field-validation-on-invalid-manual-edits.md",
        "onetest-ai Test Case link",
    )
    @pytest.mark.p2
    @pytest.mark.regression
    def test_name_field_validation_on_invalid_manual_edits(self, page):
        """Overwriting the review-form Name field with each invalid variant
        (uppercase, spaces, leading hyphen, trailing hyphen, >64 chars)
        disables "Create Skill" and shows the validation-error helper text
        (except the >64-char variant, which the native maxlength truncates
        to a valid 64-char value before validation ever sees it); a
        recovery edit back to a valid name re-enables the button; and no
        create-skill network call ever fires."""
        list_page = SkillsListPage(page)
        modal = GenerateSkillModalPage(page)

        create_skill_calls = []
        page.on(
            "request",
            lambda req: create_skill_calls.append(req.url)
            if "/elitea_core/skills/prompt_lib/" in req.url and req.method == "POST"
            else None,
        )

        # --------------------------------------------------------------
        # Step 1 — Generate a skill draft, enter the review form; the
        # unmodified (valid) draft starts with "Create Skill" enabled
        # --------------------------------------------------------------
        with allure.step("Step 1 — Generate a skill draft, enter the review form"):
            list_page.navigate_to_create()
            modal.open_modal()
            modal.fill_prompt(REVIEW_PROMPT_TEXT)

            modal.mock_generate_success(GENERATED_DRAFT_PAYLOAD)
            response = modal.click_generate_and_wait_for_response(
                timeout=GENERATE_RESPONSE_TIMEOUT
            )
            assert response.status == 200, (
                f"Expected the mocked generate-draft request to resolve 200, got {response.status}"
            )
            modal.wait_for_review_form(timeout=REVIEW_FORM_TIMEOUT)

            assert modal.get_review_name() == GENERATED_DRAFT_PAYLOAD["name"], (
                "Review form should be pre-populated with the generated draft's name"
            )
            assert modal.approve_button.is_enabled(), (
                "Create Skill should start enabled — the unmodified generated draft is itself valid"
            )

        # --------------------------------------------------------------
        # Step 2 — Uppercase name
        # --------------------------------------------------------------
        with allure.step('Step 2 — Uppercase name ("MySkill") is rejected'):
            modal.set_review_name("MySkill")

            assert modal.get_review_name() == "MySkill", (
                "Field should display the entered value verbatim, no silent lowercasing"
            )
            assert modal.get_review_name_helper_text() == NAME_VALIDATION_ERROR, (
                f"Expected the validation-error helper text, got: {modal.get_review_name_helper_text()!r}"
            )
            assert not modal.approve_button.is_enabled(), (
                "Create Skill should be disabled while the Name field is invalid (uppercase)"
            )

        # --------------------------------------------------------------
        # Step 3 — Name with spaces
        # --------------------------------------------------------------
        with allure.step('Step 3 — Name with spaces ("my skill") is rejected'):
            modal.set_review_name("my skill")

            assert modal.get_review_name_helper_text() == NAME_VALIDATION_ERROR, (
                f"Expected the validation-error helper text, got: {modal.get_review_name_helper_text()!r}"
            )
            assert not modal.approve_button.is_enabled(), (
                "Create Skill should be disabled while the Name field is invalid (spaces)"
            )

        # --------------------------------------------------------------
        # Step 4 — Leading hyphen
        # --------------------------------------------------------------
        with allure.step('Step 4 — Leading hyphen ("-my-skill") is rejected'):
            modal.set_review_name("-my-skill")

            assert modal.get_review_name_helper_text() == NAME_VALIDATION_ERROR, (
                f"Expected the validation-error helper text, got: {modal.get_review_name_helper_text()!r}"
            )
            assert not modal.approve_button.is_enabled(), (
                "Create Skill should be disabled while the Name field is invalid (leading hyphen)"
            )

        # --------------------------------------------------------------
        # Step 5 — Trailing hyphen
        # --------------------------------------------------------------
        with allure.step('Step 5 — Trailing hyphen ("my-skill-") is rejected'):
            modal.set_review_name("my-skill-")

            assert modal.get_review_name_helper_text() == NAME_VALIDATION_ERROR, (
                f"Expected the validation-error helper text, got: {modal.get_review_name_helper_text()!r}"
            )
            assert not modal.approve_button.is_enabled(), (
                "Create Skill should be disabled while the Name field is invalid (trailing hyphen)"
            )

        # --------------------------------------------------------------
        # Step 6 — Exceeds 64 characters: unreachable via manual editing.
        # The field's native maxlength truncates any input (fill() or real
        # typing) to exactly 64 chars before validation ever runs, so the
        # truncated value is valid — per AFS Known Defect #2 (case-text
        # drift, not a product defect).
        # --------------------------------------------------------------
        with allure.step("Step 6 — Name exceeding 64 chars is truncated to a valid 64-char value"):
            modal.set_review_name("a" * 70)

            truncated_name = modal.get_review_name()
            assert len(truncated_name) == 64, (
                "Native maxlength should cap the Name field at exactly 64 characters, "
                f"got length {len(truncated_name)}"
            )
            assert modal.get_review_name_helper_text() == "64/64", (
                "Truncated (valid) 64-char Name should show the plain character-count "
                f"helper text '64/64', got: {modal.get_review_name_helper_text()!r}"
            )
            assert modal.approve_button.is_enabled(), (
                "Create Skill should be enabled — the truncated 64-char Name is valid"
            )

        # --------------------------------------------------------------
        # Step 7 — Cannot create a Skill with any invalid name: recovery
        # contrast (valid name re-enables "Create Skill") + confirm zero
        # create-skill network calls fired across the whole run.
        # --------------------------------------------------------------
        with allure.step("Step 7 — Recovery to a valid name re-enables Create Skill; no Skill was ever created"):
            modal.set_review_name("my-valid-skill")

            assert modal.get_review_name_helper_text() == "14/64", (
                "Valid recovery Name should show the plain character-count helper text '14/64', "
                f"got: {modal.get_review_name_helper_text()!r}"
            )
            assert modal.approve_button.is_enabled(), (
                "Create Skill should re-enable once the Name field holds a valid value again — "
                "the disabled state is a live function of current validity, not a one-way latch"
            )
            assert not create_skill_calls, (
                "No create-skill request should ever have fired while any invalid Name was set, "
                f"got: {create_skill_calls}"
            )


# ---------------------------------------------------------------------------
# ELITEA-1992 — generated Skill name adheres to naming rules (real,
# UNMOCKED generate-draft call — see AFS Metadata "Why this test must NOT
# mock…"). No sibling test in this file asserts the naming-rule compliance
# of a real AI-generated name; every other test pre-chooses an
# already-compliant name via mock_generate_success().
# ---------------------------------------------------------------------------

GENERATED_NAME_PROMPT_TEXT = (
    "A skill that translates English customer feedback into concise "
    "Spanish summaries for the support team."
)

# Naming rule enforced client-side by validateSkillDraft() (skillDraftValidation
# .helpers.js) and, per this case, already satisfied by the real generation
# endpoint's own output.
GENERATED_NAME_RE = re.compile(r"^[a-z0-9]([a-z0-9-]*[a-z0-9])?$")

# The real, unmocked LLM-backed generate-draft call took ~25s in AFS
# exploration — a more generous timeout than the mocked-path
# GENERATE_RESPONSE_TIMEOUT (15000ms) is required here.
UNMOCKED_GENERATE_RESPONSE_TIMEOUT = 30000


class TestSkillBuildWithAIGeneratedNameNamingRules:
    """Build with AI (P2): the Skill name generated by a real, unmocked
    call to the generate-draft endpoint complies with the naming rules —
    lowercase letters/digits/hyphens only, no leading/trailing hyphen, and
    <=64 characters. Deliberately does NOT mock ``generate_skill_draft``
    (see AFS ELITEA-1992 Metadata) — mocking with a pre-chosen compliant
    name would make the assertion tautological instead of verifying the
    platform's actual AI/backend naming behavior."""

    @allure.issue(
        "https://github.com/EliteaAI/onetest-ai-tm-Elitea/blob/main/tests/automated-full-regression-ui/"
        "skills/build_with_ai/ELITEA-1992_build-with-ai-generated-skill-name-adheres-to-naming-rules.md",
        "onetest-ai Test Case link",
    )
    @pytest.mark.p2
    @pytest.mark.regression
    def test_generated_skill_name_adheres_to_naming_rules(self, page):
        """A real, unmocked generate-draft call returns a Name that is
        visible, populated, and satisfies every naming-rule sub-check —
        asserted against both the review form's displayed value and the
        raw API response body, confirming no client-side sanitization is
        silently doing the compliance work."""
        list_page = SkillsListPage(page)
        modal = GenerateSkillModalPage(page)

        # ------------------------------------------------------------
        # Step 1 — Open modal, submit prompt against the REAL backend
        # (no route mock installed for this test)
        # ------------------------------------------------------------
        with allure.step("Step 1 — Open modal, submit prompt, generate against the real backend"):
            list_page.navigate_to_create()
            modal.open_modal()
            modal.fill_prompt(GENERATED_NAME_PROMPT_TEXT)

            response = modal.click_generate_and_wait_for_response(
                timeout=UNMOCKED_GENERATE_RESPONSE_TIMEOUT
            )

            assert response.status == 200, (
                f"Expected the real generate-draft request to resolve 200, got {response.status}"
            )
            modal.wait_for_review_form(timeout=UNMOCKED_GENERATE_RESPONSE_TIMEOUT)

        # ------------------------------------------------------------
        # Step 2 — Inspect the generated Name in the review form
        # ------------------------------------------------------------
        with allure.step("Step 2 — Inspect the generated Name in the review form"):
            generated_name = modal.get_review_name()

            assert generated_name, "Generated Name field should be visible and populated"

            api_name = response.json()["name"]
            assert generated_name == api_name, (
                "Review form's displayed Name should be byte-identical to the raw "
                f"generate-draft API response's name field, got form={generated_name!r} "
                f"api={api_name!r}"
            )

        # ------------------------------------------------------------
        # Step 3 — Only lowercase letters, digits, hyphens
        # ------------------------------------------------------------
        with allure.step("Step 3 — Verify the name contains only lowercase letters, digits, hyphens"):
            assert GENERATED_NAME_RE.match(generated_name), (
                f"Generated Name {generated_name!r} must contain only lowercase letters, "
                "digits and hyphens, and must not start or end with a hyphen"
            )

        # ------------------------------------------------------------
        # Step 4 — No spaces/underscores/special characters
        # ------------------------------------------------------------
        with allure.step("Step 4 — Verify the name has no spaces, underscores, or special characters"):
            assert not re.search(r"[^a-z0-9-]", generated_name), (
                f"Generated Name {generated_name!r} must not contain spaces, underscores, "
                "or any character outside lowercase letters/digits/hyphens"
            )

        # ------------------------------------------------------------
        # Step 5 — No leading/trailing hyphen
        # ------------------------------------------------------------
        with allure.step("Step 5 — Verify the name does not start or end with a hyphen"):
            assert not generated_name.startswith("-") and not generated_name.endswith("-"), (
                f"Generated Name {generated_name!r} must not start or end with a hyphen"
            )

        # ------------------------------------------------------------
        # Step 6 — Does not exceed 64 characters
        # ------------------------------------------------------------
        with allure.step("Step 6 — Verify the name does not exceed 64 characters"):
            assert len(generated_name) <= 64, (
                f"Generated Name {generated_name!r} must not exceed 64 characters "
                f"(got {len(generated_name)})"
            )

        # Close the modal without creating a Skill — this case never clicks
        # "Create Skill" (AFS Cleanup: no skill is created/persisted).
        modal.close_button.click()


# ---------------------------------------------------------------------------
# ELITEA-1996 — "Back to prompt" from the review step returns to the input
# step and preserves the prompt text. Skills-entity sibling of ELITEA-1919
# (tests/ui/agents/test_agent_build_with_ai.py) — same shared
# GenerateEntityModal.jsx mechanism, verified independently for the Skill
# entity's own DOM/testids. All handles (`back_button`, `approve_button`,
# `review_name_input`) are pre-existing `GenerateSkillModalPage` fields;
# `back_button` was never referenced by any test in this file before this
# case. No new testids or locators added by this test.
# ---------------------------------------------------------------------------

# ELITEA-1996 — verbatim prompt per the AFS's Test Data table. This case's
# Step 4 assertion depends on reading this EXACT text back after "Back to
# prompt" is clicked, so it is a dedicated constant this test owns the
# identity of.
BACK_TO_PROMPT_PROMPT_TEXT = (
    "A skill that translates English feedback into Spanish for ELITEA-1996 "
    "back-to-prompt verification."
)

# Mocked generate_skill_draft response for ELITEA-1996 — minimal, valid
# draft shape mirroring RETRY_DRAFT_PAYLOAD/GENERATED_DRAFT_PAYLOAD above.
# This case's Pass criteria never assert on the draft's specific field
# values, only on its absence from the DOM after "Back to prompt" is
# clicked.
BACK_TO_PROMPT_DRAFT_PAYLOAD = {
    "name": "elitea-1996-back-to-prompt-draft",
    "description": "A draft used to test back-to-prompt state-preservation behavior.",
    "instructions": "You are a test skill for ELITEA-1996.",
}


class TestSkillBuildWithAIBackToPromptFromReviewStep:
    """Build with AI (P2): clicking "Back to prompt" (``back_button``) on
    the REVIEW step (after a draft has been generated) returns the modal
    to the INPUT step — review-form fields and the review-step action row
    removed from the DOM, not merely hidden — while preserving the exact
    previously-typed prompt text and firing no new network request
    (ELITEA-1996).

    ``handleBack()`` (``GenerateEntityModal.jsx``) resets ``step`` back to
    ``STEPS.INPUT`` and discards ``draftData``, but never calls
    ``setDescription('')`` — the prompt text state deliberately survives.
    Same shared component and mechanism as the Agent entity's ELITEA-1919
    (see the ELITEA-1996 AFS Triangulation section).

    ``back_button`` was previously never referenced anywhere in the skills
    test suite — this is the first test to exercise what that control
    actually does for the Skill entity."""

    @allure.issue(
        "https://github.com/EliteaAI/onetest-ai-tm-Elitea/blob/main/tests/automated-full-regression-ui/"
        "skills/build_with_ai/ELITEA-1996_build-with-ai-back-to-prompt-returns-to-input-step-without-losing-the-prompt.md",
        "onetest-ai Test Case link",
    )
    @pytest.mark.p2
    @pytest.mark.regression
    def test_back_to_prompt_returns_to_input_step_and_preserves_prompt_text(self, page):
        """Clicking "Back to prompt" from the review step returns the modal
        to the input step, preserves the exact prompt text, shows no
        leaked draft data, and fires no new network request."""
        list_page = SkillsListPage(page)
        modal = GenerateSkillModalPage(page)

        # Side-channel captures spanning the whole
        # open -> type -> generate -> back sequence (AFS Expected Results /
        # Axis 2) — started before Step 1 so nothing fired during
        # modal-open itself is missed.
        console_capture = modal.capture_console_errors()
        draft_requests = modal.capture_requests_matching(
            "/elitea_core/generate_skill_draft/", method="POST"
        )
        create_requests = modal.capture_requests_matching(
            "/elitea_core/skills/prompt_lib/", method="POST"
        )

        modal.mock_generate_success(BACK_TO_PROMPT_DRAFT_PAYLOAD)

        try:
            with allure.step("Step 1 — Generate a draft and reach the review form"):
                list_page.navigate_to_create()
                modal.open_modal()
                modal.fill_prompt(BACK_TO_PROMPT_PROMPT_TEXT)

                assert modal.get_prompt_value() == BACK_TO_PROMPT_PROMPT_TEXT, (
                    "Prompt textarea should contain exactly the entered text"
                )

                with modal.expect_generate_response(timeout=GENERATE_RESPONSE_TIMEOUT) as response_info:
                    modal.generate_button.click()
                assert response_info.value.status == 200, (
                    "Mocked generate-draft response should resolve 200 to reach the review step"
                )
                modal.wait_for_review_form(timeout=REVIEW_FORM_TIMEOUT)

                assert modal.get_review_name() == BACK_TO_PROMPT_DRAFT_PAYLOAD["name"], (
                    "Review form should display the generated draft's name before Back discards it"
                )
                assert len(draft_requests) == 1, (
                    f"Exactly one generate-draft call should have fired to reach the review step, "
                    f"got: {list(draft_requests)}"
                )

            with allure.step("Step 2 — Click 'Back to prompt'"):
                modal.back_button.click()

            with allure.step("Step 3 — Verify the modal returns to the prompt input step"):
                modal.wait_for_input_step(timeout=NAVIGATION_TIMEOUT)
                assert modal.back_button.count() == 0, (
                    "'Back to prompt' button should be fully removed from the DOM after Back, "
                    "not merely hidden — the review-step action row is gone entirely"
                )
                assert modal.approve_button.count() == 0, (
                    "'Create Skill' button should be fully removed from the DOM after Back"
                )

            with allure.step("Step 4 — Verify the previously entered prompt text is preserved"):
                assert modal.get_prompt_value() == BACK_TO_PROMPT_PROMPT_TEXT, (
                    "Prompt textarea should show the exact original text after Back — no "
                    "truncation, no whitespace drift, no residual draft text appended"
                )

            with allure.step("Step 5 — Verify no draft data leaks into the prompt step UI"):
                assert modal.review_name_input.count() == 0, (
                    "Review-form Name field should be fully removed from the DOM after Back — "
                    "no leaked draft data reachable via direct DOM query"
                )
                assert modal.review_description_input.count() == 0, (
                    "Review-form Description field should be fully removed from the DOM after Back"
                )
                assert modal.review_instructions_input.count() == 0, (
                    "Review-form Instructions field should be fully removed from the DOM after Back"
                )

            with allure.step(
                "Step 6 — Verify no new network requests and zero console errors"
            ):
                assert len(draft_requests) == 1, (
                    "Back click itself must not fire a new generate-draft call — still exactly "
                    f"the one from Step 1, got: {list(draft_requests)}"
                )
                assert not create_requests, (
                    f"Back click must never fire the CREATE skill call, got: {list(create_requests)}"
                )
                assert not console_capture, (
                    f"Expected zero console errors across the whole flow, got: {list(console_capture)}"
                )
        finally:
            modal.clear_generate_mock()
            console_capture.stop()
            draft_requests.stop()
            create_requests.stop()
