name: Delete stale branches

on:
  workflow_dispatch:
  schedule:
    # - cron: "*/6 * * * *"
    - cron: "0 0 * * *" # Everday at midnight

jobs:
  remove-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Stale Branches
        uses: fpicalausa/remove-stale-branches@v2.1.0
        with:
          dry-run: false
          ignore-branches-with-open-prs: true
          days-before-branch-stale: 20
          operations-per-run: 100
          ignore-unknown-authors: true
          default-recipient: ${{ github.repository_owner }}
